// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cx_read_sas7bdat
SEXP cx_read_sas7bdat(std::string path);
RcppExport SEXP _clinXport_cx_read_sas7bdat(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cx_read_sas7bdat(path));
    return rcpp_result_gen;
END_RCPP
}
// cx_write_sas7bdat
SEXP cx_write_sas7bdat(DataFrame df, std::string path, std::string dataset_name, Nullable<CharacterVector> var_labels, Nullable<CharacterVector> var_formats, Nullable<IntegerVector> var_lengths);
RcppExport SEXP _clinXport_cx_write_sas7bdat(SEXP dfSEXP, SEXP pathSEXP, SEXP dataset_nameSEXP, SEXP var_labelsSEXP, SEXP var_formatsSEXP, SEXP var_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset_name(dataset_nameSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type var_labels(var_labelsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type var_formats(var_formatsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type var_lengths(var_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(cx_write_sas7bdat(df, path, dataset_name, var_labels, var_formats, var_lengths));
    return rcpp_result_gen;
END_RCPP
}
// cx_write_xpt
SEXP cx_write_xpt(DataFrame df, std::string path, int version, std::string dataset_name, std::string dataset_label, Nullable<CharacterVector> var_labels, Nullable<CharacterVector> var_formats, Nullable<IntegerVector> var_lengths);
RcppExport SEXP _clinXport_cx_write_xpt(SEXP dfSEXP, SEXP pathSEXP, SEXP versionSEXP, SEXP dataset_nameSEXP, SEXP dataset_labelSEXP, SEXP var_labelsSEXP, SEXP var_formatsSEXP, SEXP var_lengthsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset_name(dataset_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type dataset_label(dataset_labelSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type var_labels(var_labelsSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type var_formats(var_formatsSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type var_lengths(var_lengthsSEXP);
    rcpp_result_gen = Rcpp::wrap(cx_write_xpt(df, path, version, dataset_name, dataset_label, var_labels, var_formats, var_lengths));
    return rcpp_result_gen;
END_RCPP
}
// cx_read_xpt
SEXP cx_read_xpt(std::string path);
RcppExport SEXP _clinXport_cx_read_xpt(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cx_read_xpt(path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clinXport_cx_read_sas7bdat", (DL_FUNC) &_clinXport_cx_read_sas7bdat, 1},
    {"_clinXport_cx_write_sas7bdat", (DL_FUNC) &_clinXport_cx_write_sas7bdat, 6},
    {"_clinXport_cx_write_xpt", (DL_FUNC) &_clinXport_cx_write_xpt, 8},
    {"_clinXport_cx_read_xpt", (DL_FUNC) &_clinXport_cx_read_xpt, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_clinXport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
