# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read a SAS7BDAT file into a data frame
#'
#' @param path Path to the .sas7bdat file.
#' @return A data.frame with metadata attributes (`var_labels`, `var_formats`, `var_lengths`, `dataset_name`).
#' @keywords internal
#' @export
cx_read_sas7bdat <- function(path) {
    .Call(`_clinXport_cx_read_sas7bdat`, path)
}

#' Write a data frame to SAS7BDAT format (uncompressed)
#'
#' @param df           Data frame to write.
#' @param path         Output .sas7bdat file path.
#' @param dataset_name SAS dataset name (≤64 chars).
#' @param var_labels   Named character vector of variable labels.
#' @param var_formats  Named character vector of SAS format strings.
#' @param var_lengths  Named integer vector of character variable lengths (numerics always 8).
#' @return Invisibly returns `path`.
#' @keywords internal
#' @export
cx_write_sas7bdat <- function(df, path, dataset_name = "DATASET", var_labels = NULL, var_formats = NULL, var_lengths = NULL) {
    .Call(`_clinXport_cx_write_sas7bdat`, df, path, dataset_name, var_labels, var_formats, var_lengths)
}

#' Write a data frame to SAS XPT format (v5 or v8)
#'
#' @param df          A data.frame to export.
#' @param path        Output file path (character).
#' @param version     XPT version: 5 (default) or 8.
#' @param dataset_name SAS dataset name (≤8 chars for v5, ≤32 for v8).
#' @param dataset_label Dataset label (≤40 chars).
#' @param var_labels  Named character vector of variable labels.
#' @param var_formats Named character vector of SAS format strings (e.g. "DATE9.").
#' @param var_lengths Named integer vector of variable byte lengths.
#' @return Invisibly returns `path`.
#' @keywords internal
#' @export
cx_write_xpt <- function(df, path, version = 5L, dataset_name = "DATASET", dataset_label = "", var_labels = NULL, var_formats = NULL, var_lengths = NULL) {
    .Call(`_clinXport_cx_write_xpt`, df, path, version, dataset_name, dataset_label, var_labels, var_formats, var_lengths)
}

#' Read a SAS XPT file (v5 or v8) into a data frame
#'
#' @param path Path to the .xpt file.
#' @return A data.frame with attributes: `var_labels`, `var_formats`, `var_lengths`, `dataset_name`, `dataset_label`.
#' @keywords internal
#' @export
cx_read_xpt <- function(path) {
    .Call(`_clinXport_cx_read_xpt`, path)
}

